name : Java CI with Maven - Test and package #test
on:
  pull_request:
    branches:
        - main
jobs:
  BuildJava:
    name : BuildJava
    runs-on: ubuntu-latest
    steps:
      - name : SetCurrentRepository
        uses: actions/checkout@v4
      - name : SetUpJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name : BuildMaven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
            -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')
